# Generated by Django 4.2 on 2024-04-25 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('refsystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecode',
            name='code',
            field=models.CharField(blank=True, max_length=6, verbose_name='Личный инвайт-код пользователя'),
        ),
        migrations.AlterField(
            model_name='usedcode',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='used_code', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, который использует инвайт-код'),
        ),
    ]
